apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-techchallenge
  labels:
    app: food-techchallenge
spec:
  template:
    metadata:
      name: food-techchallenge
      labels:
        app: food-techchallenge
    spec:
      containers:
        - name: mysqldb
          image: 'mysql:8.0'
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: 'food_techchallenge'
            - name: MYSQL_PASSWORD
              value: '170593'
            - name: MYSQL_ROOT_PASSWORD
              value: '170593'
        - name: food-techchallenge-container-app
          image: raulima1/food_techchallenge
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:mysql://food-techchallenge-svc:3306/food_techchallenge?createDatabaseIfNotExist=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2'
            - name: SPRING_DATASOURCE_USERNAME
              value: 'root'
            - name: SPRING_DATASOURCE_PASSWORD
              value: '170593'
          resources:
            requests:
              cpu: 400m
  replicas: 1
  selector:
    matchLabels:
      app: food-techchallenge