apiVersion: v1
kind: Service
metadata:
  name: food-techchallenge-svc
spec:
  type: NodePort
  selector:
    app: food-techchallenge
  ports:
    - protocol: TCP
      name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30000
    - protocol: TCP
      name: app
      port: 8080
      targetPort: 8080